# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  key: <%= ENV['SCOUT_KEY'] %>
  host: http://scoutapp.ngrok.io

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  # log_level: debug

  # name: Application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  # name:

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true
  # name: Rails4 - summary_metrics_for_middleware - NR MR Disabled
  name: Rails4 - Load Test

production:
  <<: *defaults
  monitor: true

development:
  <<: *defaults
  log_level: debug

test:
  <<: *defaults
  monitor: false